# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-Asterisk-Manager
version:      0.06
version_from: Manager.pm
installdirs:  site
requires:
    Digest::MD5:                   2.2
    POE:                           0.1203
    POE::Component::Client::TCP:   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
