--- #YAML:1.0
name:                POE-Component-Client-Asterisk-Manager
version:             0.08
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Digest::MD5:                   2.2
    POE:                           0.1203
    POE::Component::Client::TCP:   
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
